In [1]:
import pandas as pd

### Dataset com 1303 descrições e preços de notebooks (2018), com preços em Euros. Existem inúmeros datasets no Kaggle com esta temática e podem ser adaptados/utilizados para estudos: https://www.kaggle.com/ionaskel/laptop-prices

In [7]:
df = pd.read_csv('../datasets/laptops.csv', encoding='utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4: invalid continuation byte

In [3]:
df.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros)
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45"
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60"

In [4]:
df.columns

Index(['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen',
       'CPU', 'RAM', ' Storage', 'GPU', 'Operating System',
       'Operating System Version', 'Weight', 'Price (Euros)'],
      dtype='object')

In [5]:
df.shape

(1303, 13)

In [6]:
df.dtypes

Manufacturer                object
Model Name                  object
Category                    object
Screen Size                 object
Screen                      object
CPU                         object
RAM                         object
 Storage                    object
GPU                         object
Operating System            object
Operating System Version    object
Weight                      object
Price (Euros)               object
dtype: object

In [7]:
def mod_cols(col):
    #remove espaços em branco ao redor
    col = col.strip()
    #remove parenteses
    col = col.replace('(', '')
    col = col.replace(')', '')
    #passa para minusculo
    col = col.lower()
    #preenche espaço entre palavras com _
    col = col.replace(' ', '_')
    return col
    
df.columns = [mod_cols(c) for c in df.columns]
df.columns
#df.columns.tolist()

Index(['manufacturer', 'model_name', 'category', 'screen_size', 'screen',
       'cpu', 'ram', 'storage', 'gpu', 'operating_system',
       'operating_system_version', 'weight', 'price_euros'],
      dtype='object')

In [8]:
df['screen_size'] = (df['screen_size'].str.replace('"', ''))

In [9]:
df['screen_size'] = df['screen_size'].astype(float)

In [10]:
df['screen_size']

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1298    14.0
1299    13.3
1300    14.0
1301    15.6
1302    15.6
Name: screen_size, Length: 1303, dtype: float64

In [11]:
def mod_weight(w):
    w = w.strip()
    #alguns lugares tem kg, noutros kgs
    w = w.replace('kg', '')
    w = w.replace('s', '')
    w = float(w)
    return w

df['weight'] = [mod_weight(w) for w in df['weight']]
df['weight']

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298    1.80
1299    1.30
1300    1.50
1301    2.19
1302    2.20
Name: weight, Length: 1303, dtype: float64

In [12]:
#df['weight'] = df['weight'].str.replace('kg', '')
#df['weight'] = df['weight'].str.replace('s', '').astype(float)
#df['weight']

In [13]:
df['storage'].str.split(n=1)

0                 [128GB, SSD]
1       [128GB, Flash Storage]
2                 [256GB, SSD]
3                 [512GB, SSD]
4                 [256GB, SSD]
                 ...
1298              [128GB, SSD]
1299              [512GB, SSD]
1300     [64GB, Flash Storage]
1301                [1TB, HDD]
1302              [500GB, HDD]
Name: storage, Length: 1303, dtype: object

In [14]:
df['storage'].str.split(n=1, expand=True)

          0              1
0     128GB            SSD
1     128GB  Flash Storage
2     256GB            SSD
3     512GB            SSD
4     256GB            SSD
...     ...            ...
1298  128GB            SSD
1299  512GB            SSD
1300   64GB  Flash Storage
1301    1TB            HDD
1302  500GB            HDD

[1303 rows x 2 columns]

In [15]:
df_sto = df['storage'].str.split(n=1, expand=True)

In [16]:
df_sto

          0              1
0     128GB            SSD
1     128GB  Flash Storage
2     256GB            SSD
3     512GB            SSD
4     256GB            SSD
...     ...            ...
1298  128GB            SSD
1299  512GB            SSD
1300   64GB  Flash Storage
1301    1TB            HDD
1302  500GB            HDD

[1303 rows x 2 columns]

In [17]:
df_sto.columns = ['A', 'B']

In [18]:
df_sto

          A              B
0     128GB            SSD
1     128GB  Flash Storage
2     256GB            SSD
3     512GB            SSD
4     256GB            SSD
...     ...            ...
1298  128GB            SSD
1299  512GB            SSD
1300   64GB  Flash Storage
1301    1TB            HDD
1302  500GB            HDD

[1303 rows x 2 columns]

In [19]:
df.insert(8, 'storage_type', df_sto['B'])

In [20]:
df['storage'] = df_sto['A']
df.head()

,manufacturer,model_name,category,screen_size,screen,cpu,ram,storage,storage_type,gpu,operating_system,operating_system_version,weight,price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB,SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37,"1339,69"
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB,Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34,"898,94"
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB,SSD,Intel HD Graphics 620,No OS,NaN,1.86,"575,00"
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB,SSD,AMD Radeon Pro 455,macOS,NaN,1.83,"2537,45"
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB,SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37,"1803,60"

In [21]:
df.loc[76:81,'storage']

76      2TB
77    128GB
78      1TB
79    128GB
80    256GB
81    512GB
Name: storage, dtype: object

In [22]:
df.head()

,manufacturer,model_name,category,screen_size,screen,cpu,ram,storage,storage_type,gpu,operating_system,operating_system_version,weight,price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB,SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37,"1339,69"
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB,Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34,"898,94"
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB,SSD,Intel HD Graphics 620,No OS,NaN,1.86,"575,00"
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB,SSD,AMD Radeon Pro 455,macOS,NaN,1.83,"2537,45"
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB,SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37,"1803,60"

In [23]:
import numpy as np
df2 = pd.DataFrame(np.random.randn(7,3))

In [24]:
df2

          0         1         2
0 -0.785469  0.658364  2.233688
1  1.311348  0.014109  0.586213
2  2.089794  0.218347  1.987054
3 -0.399068 -0.103324  0.144074
4  1.033531  0.434264 -0.544805
5 -0.131501 -1.075181 -0.860463
6 -1.264162 -1.865907  0.855641

In [25]:
df2.iloc[:4,1] = np.nan
df2.iloc[:2,2] = np.nan
df2

          0         1         2
0 -0.785469       NaN       NaN
1  1.311348       NaN       NaN
2  2.089794       NaN  1.987054
3 -0.399068       NaN  0.144074
4  1.033531  0.434264 -0.544805
5 -0.131501 -1.075181 -0.860463
6 -1.264162 -1.865907  0.855641

In [26]:
df2.fillna(0)

          0         1         2
0 -0.785469  0.000000  0.000000
1  1.311348  0.000000  0.000000
2  2.089794  0.000000  1.987054
3 -0.399068  0.000000  0.144074
4  1.033531  0.434264 -0.544805
5 -0.131501 -1.075181 -0.860463
6 -1.264162 -1.865907  0.855641

In [27]:
df2.fillna({1:0.5, 2: -1}) # índice da coluna: valor a preencher nos NaN desta coluna

          0         1         2
0 -0.785469  0.500000 -1.000000
1  1.311348  0.500000 -1.000000
2  2.089794  0.500000  1.987054
3 -0.399068  0.500000  0.144074
4  1.033531  0.434264 -0.544805
5 -0.131501 -1.075181 -0.860463
6 -1.264162 -1.865907  0.855641

In [28]:
df2.fillna(df2.loc[:,0].mean()) # preenche com média da coluna 0

          0         1         2
0 -0.785469  0.264925  0.264925
1  1.311348  0.264925  0.264925
2  2.089794  0.264925  1.987054
3 -0.399068  0.264925  0.144074
4  1.033531  0.434264 -0.544805
5 -0.131501 -1.075181 -0.860463
6 -1.264162 -1.865907  0.855641

In [29]:
df.head()

,manufacturer,model_name,category,screen_size,screen,cpu,ram,storage,storage_type,gpu,operating_system,operating_system_version,weight,price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB,SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37,"1339,69"
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB,Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34,"898,94"
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB,SSD,Intel HD Graphics 620,No OS,NaN,1.86,"575,00"
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB,SSD,AMD Radeon Pro 455,macOS,NaN,1.83,"2537,45"
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB,SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37,"1803,60"

In [30]:
df.fillna('-')

,manufacturer,model_name,category,screen_size,screen,cpu,ram,storage,storage_type,gpu,operating_system,operating_system_version,weight,price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB,SSD,Intel Iris Plus Graphics 640,macOS,-,1.37,"1339,69"
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB,Flash Storage,Intel HD Graphics 6000,macOS,-,1.34,"898,94"
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB,SSD,Intel HD Graphics 620,No OS,-,1.86,"575,00"
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB,SSD,AMD Radeon Pro 455,macOS,-,1.83,"2537,45"
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB,SSD,Intel Iris Plus Graphics 650,macOS,-,1.37,"1803,60"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB,SSD,Intel HD Graphics 520,Windows,10,1.80,"638,00"
1299,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB,SSD,Intel HD Graphics 520,Windows,10,1.30,"1499,00"
1300,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB,Flash Storage,Intel HD Graphics,Windows,10,1.50,"229,00"
1301,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB,HDD,AMD Radeon R5 M330,Windows,10,2.19,"764,00"
1302,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB,HDD,Intel HD Graphics,Windows,10,2.20,"369,00"

In [1]:
import numpy as np
import pandas as pd
data = {'pedro': 'pedro@gmail.com', 'josenalde': 'josenalde.oliveira@ufrn.br', 'david': 'david3@gmail.com', 'paulo': np.nan}
data

{'pedro': 'pedro@gmail.com',
 'josenalde': 'josenalde.oliveira@ufrn.br',
 'david': 'david3@gmail.com',
 'paulo': nan}

In [4]:
df = pd.Series(data=data)

In [5]:
df

pedro                   pedro@gmail.com
josenalde    josenalde.oliveira@ufrn.br
david                  david3@gmail.com
paulo                               NaN
dtype: object

In [6]:
df.str.contains('gmail')

pedro         True
josenalde    False
david         True
paulo          NaN
dtype: object